name: Android CI (Debug APK)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v3

    - name: Ensure platform + build-tools
      run: |
        sdkmanager --install "platforms;android-34" "platform-tools" "build-tools;34.0.0" || true
        yes | sdkmanager --licenses || true

    - name: Bootstrap Gradle wrapper (8.7) if missing
      run: |
        if [ ! -f gradlew ]; then
          curl -sL -o /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q /tmp/gradle.zip -d "$HOME/gradle"
          "$HOME/gradle/gradle-8.7/bin/gradle" wrapper --gradle-version 8.7
        fi
        chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew --no-daemon --stacktrace assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
