name: Android Debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare project if missing (one-time bootstrap)
        run: |
          if [ ! -f settings.gradle ]; then
            echo "rootProject.name = 'JarvisApp'" > settings.gradle
          fi
          if [ ! -d app ]; then
            mkdir -p app/src/main/{java/com/jarvis/app,assets}
            cat > app/build.gradle <<'G'
plugins {
  id 'com.android.application'
}
android {
  namespace 'com.jarvis.app'
  compileSdk 34
  defaultConfig {
    applicationId "com.jarvis.app"
    minSdk 26
    targetSdk 34
    versionCode 1
    versionName "1.0"
  }
  buildTypes {
    release { minifyEnabled false }
  }
}
dependencies { }
G
            cat > build.gradle <<'G'
buildscript { repositories { google(); mavenCentral() } dependencies { } }
allprojects { repositories { google(); mavenCentral() } }
G
            cat > app/src/main/AndroidManifest.xml <<'M'
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.jarvis.app">
  <application android:label="Jarvis" android:allowBackup="true">
    <activity android:name=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
M
            mkdir -p app/src/main/java/com/jarvis/app
            cat > app/src/main/java/com/jarvis/app/MainActivity.java <<'J'
package com.jarvis.app;
import android.app.Activity;
import android.os.Bundle;
import android.webkit.WebView;
import android.webkit.WebSettings;
public class MainActivity extends Activity {
  @Override protected void onCreate(Bundle savedInstanceState){
    super.onCreate(savedInstanceState);
    WebView w = new WebView(this);
    WebSettings s = w.getSettings();
    s.setJavaScriptEnabled(true);
    s.setDomStorageEnabled(true);
    w.loadUrl("file:///android_asset/index.html");
    setContentView(w);
  }
}
J
            cat > app/src/main/assets/index.html <<'H'
<!doctype html><meta charset="utf-8"><title>Jarvis</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<body style="font-family:sans-serif;background:#0b0b10;color:#eee;">
<h2>Jarvis</h2><p>Android WebView bootstrap. Replace with your UI later.</p>
</body>
H
          fi

      - name: Make gradlew
        run: |
          ./gradlew --version 2>/dev/null || true
          if [ ! -f gradlew ]; then
            ./gradlew wrapper --gradle-version 8.7 || true
          fi

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
